### ISSUE TITLE
It is a great work! Can you explain it here? self.attention_size = 16

### ISSUE THREAD

**Issue by c1a1o1** [christiancosgrove/pytorch-sagan#1]
self.attention_size = 16   why??
        self.att = SelfAttention(128, self.attention_size)    why??
        self.att_post = SelfAttentionPost(128, self.attention_size)  why??

**Comment by christiancosgrove** [comment]
Sorry for the late response. If you go to Eq. 2 of the [paper](https://arxiv.org/pdf/1805.08318.pdf), `self.attention_size` corresponds to the number of channels of the embedding convolution operations, denoted C_bar. The authors of SAGAN say that they used C_bar = C/8 for all experiments, where C is the number of output channels of the self-attention operation. 

In this case, since we want our self-attention layer to have 128 output channels, so we use C_bar (=`self.attention_size`) = 128/8 = 16.

Hope this helps.

**Comment by c1a1o1** [comment]
Thank you very much!
